### ISSUE TITLE
Job run failed, but Dry run is successful

### ISSUE THREAD

**Issue by ksoufan** [nautobot/nautobot-plugin-ssot-arista-cloudvision#119]
### Environment
* Python version:  3.10.8
* Nautobot version:  1.4.7
* aristacv-sync version:  1.4.0

Sync completed

Getting IndexError 
Dry run is successful

**Comment by jdrew82** [comment]
Can you please provide the traceback? I need to know where in the code it's throwing the IndexError.

**Comment by ksoufan** [comment]
Below is the traceback, not sure if it's related to issue #116 

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 332, in run
    self.sync_data()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 167, in sync_data
    self.execute_sync()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 95, in execute_sync
    self.source_adapter.sync_to(self.target_adapter, flags=self.diffsync_flags)
  File "/opt/nautobot/lib/python3.10/site-packages/diffsync/__init__.py", line 546, in sync_to
    target.sync_from(self, diff_class=diff_class, flags=flags, callback=callback, diff=diff)
  File "/opt/nautobot/lib/python3.10/site-packages/diffsync/__init__.py", line 524, in sync_from
    result = syncer.perform_sync()
  File "/opt/nautobot/lib/python3.10/site-packages/diffsync/helpers.py", line 326, in perform_sync
    changed |= self.sync_diff_element(element)
  File "/opt/nautobot/lib/python3.10/site-packages/diffsync/helpers.py", line 366, in sync_diff_element
    changed, modified_model = self.sync_model(src_model=src_model, dst_model=dst_model, ids=ids, attrs=attrs)
  File "/opt/nautobot/lib/python3.10/site-packages/diffsync/helpers.py", line 415, in sync_model
    dst_model = self.model_class.create(diffsync=self.dst_diffsync, ids=ids, attrs=attrs)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/diffsync/models/nautobot.py", line 43, in create
    site_code, role_code = nautobot.parse_hostname(ids["name"].lower())
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/utils/nautobot.py", line 127, in parse_hostname
    if match.group("site"):
IndexError: no such group

**Comment by ksoufan** [comment]
@jdrew82 Were you able to find the issue in the nautobot model?

**Comment by jdrew82** [comment]
@ksoufan I've not had a chance to look into this one yet. I'll try to take a look today or tomorrow. It's a bit of an odd error. What do you have in your `hostname_patterns` setting? I'm going to guess that you don't have a capture group that has the site key.

**Comment by ksoufan** [comment]
Yep, the Nautobot instance is a fresh installed and trying to pull all from cloudvision.

**Comment by jdrew82** [comment]
@ksoufan Can you please share your settings for the plugin from `nautobot_config.py`?

**Comment by jdrew82** [comment]
Actually, nevermind. I've recreated this in my unit tests. It's definitely because there's no capture group in your `hostname_patterns` setting using the site key.

**Comment by jdrew82** [comment]
@ksoufan can you confirm if this is still an issue or not?

**Comment by ksoufan** [comment]
@jdrew82 I tried upgrading the plugin but I got the same version, how do I install this fix?

**Comment by jdrew82** [comment]
@ksoufan We've got a new release cut and pushed to PyPI so you should be able to install from there. That should address your issue and we can close this out.

**Comment by qduk** [comment]
@ksoufan did updating resolve your issue?

**Comment by qduk** [comment]
@ksoufan I'm closing this as there hasn't been a response in awhile. If there is still an issue, please open an issue on the aggregate [nautobot-ssot](https://github.com/nautobot/nautobot-plugin-ssot) app.
