### ISSUE TITLE
Exception when upgrading to nautobot 1.5.7

### ISSUE THREAD

**Issue by erjac77** [nautobot/nautobot-plugin-ssot-arista-cloudvision#133]
### Environment
* Python version:  3.9.13
* Nautobot version:  1.4.8 -> 1.5.7
* aristacv-sync version:  1.5.0

### Expected Behavior
When upgrading the Docker image of Nautobot from 1.4.8 to 1.5.7, the `post_migrate_create_custom_fields` command should passed successfully. The command is run automatically by the container.

### Observed Behavior
Instead, an exception occurred complaining about a duplicate key.

```
During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "extras_customfield_name_key"
DETAIL:  Key (name)=(arista_eostrain) already exists.

 


The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/nautobot/core/cli.py", line 54, in main
    run_app(
  File "/usr/local/lib/python3.9/site-packages/nautobot/core/runner/runner.py", line 263, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/nautobot/core/management/commands/post_upgrade.py", line 78, in handle
    call_command(
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 268, in handle
    emit_post_migrate_signal(
  File "/usr/local/lib/python3.9/site-packages/django/core/management/sql.py", line 42, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/local/lib/python3.9/site-packages/nautobot_ssot_aristacv/signals.py", line 83, in post_migrate_create_custom_fields
    field, _ = CustomField.objects.get_or_create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
```

### Steps to Reproduce
1. Install Nautobot 1.4.8
2. Install the nautobot_ssot_aristacv plugin
3. Upgrade Nautobot to 1.5.7

**Comment by jdrew82** [comment]
This would most likely be because we're using signals to create the Custom Fields upon the initial start of the App. I don't believe you should need to run the post_migrate command to force them to be created.

**Comment by erjac77** [comment]
@jdrew82 One thing I forgot to mention is that we are using the Nautobot Docker image.

**Comment by jdrew82** [comment]
If you're using Docker containers I'd advise that you rebuild them. You shouldn't need to run any post_migrate commands after upgrading.

**Comment by erjac77** [comment]
We build Nautobot with all the plugins according to the instructions found here:
https://github.com/nautobot/nautobot-docker-compose/tree/main/plugin_example

Moreover, I don't see in [docs ](https://docs.nautobot.com/projects/core/en/stable/docker/#docker-only-configuration) an option to skip the `post_migrate` command.

**Comment by jdrew82** [comment]
Perhaps I misunderstood. I thought from your original comment that you had executed the `post_migrate_create_custom_fields` after you had upgraded, ie rebuilt your containers for the newer version. If you're stating that you had simply started the containers and that command ran automatically and threw the error, that's different.

**Comment by erjac77** [comment]
Sorry for the misunderstood. It's the latter.

> If you're stating that you had simply started the containers and that command ran automatically and threw the error, that's different.

**Comment by jdrew82** [comment]
Let me see if I can recreate the issue then. It sounds like the signal that creates the CustomFields is being triggered after the upgrade and that shouldn't happen.

**Comment by jdrew82** [comment]
I've attempted to recreate the issue with a fresh environment and I'm not seeing the error that you are. I used the development environment in this project to first build using Nautobot 1.4.7 and python 3.9 and then updated it to use Nautobot 1.5.7. I'm not seeing any post_migrate command being run. I do see some migrations but nothing that triggers the error you're citing.

```
aristacv-sync-nautobot-1       | Running migrations:
aristacv-sync-nautobot-1       |   Applying extras.0049_alter_tag_slug... OK
aristacv-sync-nautobot-1       |   Applying extras.0050_customfield_grouping... OK
aristacv-sync-nautobot-1       |   Applying extras.0051_add_job_task_queues... OK
aristacv-sync-nautobot-1       |   Applying dcim.0017_locationtype_nestable... OK
aristacv-sync-nautobot-1       |   Applying dcim.0018_device_redundancy_group... OK
aristacv-sync-nautobot-1       |   Applying dcim.0019_device_redundancy_group_data_migration...
aristacv-sync-nautobot-1       |     Model dcim.DeviceRedundancyGroup
aristacv-sync-nautobot-1       |       Linking to existing status Planned (planned)
aristacv-sync-nautobot-1       |       Linking to existing status Staging (staging)
aristacv-sync-nautobot-1       |       Linking to existing status Active (active)
aristacv-sync-nautobot-1       |       Linking to existing status Decommissioning (decommissioning)
aristacv-sync-nautobot-1       |       Linking to existing status Retired (retired)
aristacv-sync-nautobot-1       |     Added 0, linked 5 status records
aristacv-sync-nautobot-1       |  OK
aristacv-sync-nautobot-1       |   Applying extras.0052_configcontext_device_redundancy_groups... OK
aristacv-sync-nautobot-1       |   Applying extras.0053_relationship_required_on... OK
aristacv-sync-nautobot-1       |   Applying taggit.0004_alter_taggeditem_content_type_alter_taggeditem_tag... OK
aristacv-sync-nautobot-1       |   Applying taggit.0005_auto_20220424_2025... OK
aristacv-sync-nautobot-1       | 18:27:20.504 INFO    nautobot.extras.utils utils.py        refresh_job_model_from_job_class() :
aristacv-sync-nautobot-1       |   Refreshed Job "SSoT - Arista CloudVision: CloudVision ⟹ Nautobot" from <plugins: CloudVisionDataSource>
aristacv-sync-nautobot-1       | 18:27:20.509 INFO    nautobot.extras.utils utils.py        refresh_job_model_from_job_class() :
aristacv-sync-nautobot-1       |   Refreshed Job "SSoT - Arista CloudVision: Nautobot ⟹ CloudVision" from <plugins: CloudVisionDataTarget>
aristacv-sync-nautobot-1       | 18:27:20.513 INFO    nautobot.extras.utils utils.py        refresh_job_model_from_job_class() :
aristacv-sync-nautobot-1       |   Refreshed Job "Device/Software Lifecycle Reporting: Device Software Validation Report" from <plugins: DeviceSoftwareValidationFullReport>
aristacv-sync-nautobot-1       | 18:27:20.526 INFO    nautobot.extras.utils utils.py        refresh_job_model_from_job_class() :
aristacv-sync-nautobot-1       |   Refreshed Job "Device/Software Lifecycle Reporting: Inventory Item Software Validation Report" from <plugins: InventoryItemSoftwareValidationFullReport>
aristacv-sync-nautobot-1       | 18:27:20.547 INFO    nautobot.extras.utils utils.py        refresh_job_model_from_job_class() :
aristacv-sync-nautobot-1       |   Refreshed Job "CVE Tracking: Generate Vulnerabilities" from <plugins: GenerateVulnerabilities>
```

Can you share the logs from your container startup that shows the error occurring? If nothing else, you could delete the CustomFields and just restart and that should resolve it.

**Comment by jdrew82** [comment]
I think that #143 and this one are related.

**Comment by jdrew82** [comment]
This should be resolved now. Please confirm you're no longer seeing the issue.

**Comment by erjac77** [comment]
Hi Justin, sorry for the delay. I can't share my container logs because we dropped and rebuilt the database and I couldn't find time to recreate the issue. Problem #143 and this one seem definitely related. Thanks for the fix.
