### ISSUE TITLE
cloudvision -> nautobot indexerror: list index out of range

### ISSUE THREAD

**Issue by ddrew83** [nautobot/nautobot-plugin-ssot-arista-cloudvision#137]
Python version: 3.10	Nautobot version: 1.5.7	nautobot_ssot_aristacv 1.4.0	ssot : 1.2.0
Steps to Reproduce
1.Plugins, dashboard, single source of truth
2.Cloudvision --> Nautobot
3. Debug and Dry run, Run job now

Pull data from CVP into Nautobot, or at least show me what its going to pull in.

After several logs entries showing interface details for each device-
Loading data from Nautobot
Then a failure - An exception occurred: IndexError: list index out of range

Traceback (most recent call last):
File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 332, in run
self.sync_data()
File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 146, in sync_data
self.load_target_adapter()
File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/jobs.py", line 123, in load_target_adapter
self.target_adapter.load()
File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/diffsync/adapters/nautobot.py", line 41, in load
version=nautobot.get_device_version(dev),
File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/utils/nautobot.py", line 107, in get_device_version
version = relations["destination"][software_relation][0].source.version
File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/query.py", line 318, in getitem
return qs._result_cache[0]
IndexError: list index out of range

**Comment by jdrew82** [comment]
Looks to be an issue with a missing Relationship to a SoftwareVersion in the DLC App. This should be fixed now though with the latest release.

**Comment by ddrew83** [comment]
thanks, I actually configured another nautobot instance and left the BGP and DLC app off and its getting further now. Just an issue with the name- nautobot.dcim.models.sites.Site.DoesNotExist: Site matching query does not exist. Do you have an example of the hostname patterns?
I will try to figure it out in mean time

**Comment by jdrew82** [comment]
There is an example of the hostname pattern and site mapping settings in the [nautobot_config.py](https://github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision/blob/9575f0eadd3bc44f1927a9e9c0f711c3580ac566/development/nautobot_config.py#L88) file in the development folder of this project. Basically, it uses named capture groups in the `hostname_pattern` setting to define what part of the hostname to use for determining your site or role and then uses the `site_mappings` and `role_mappings` settings to specify the name of the Site or Device role to assign the Device.

**Comment by jdrew82** [comment]
@ddrew83 Is this still an issue?
