### ISSUE TITLE
Sync SSOT very slow 

### ISSUE THREAD

**Issue by nsicard514** [nautobot/nautobot-plugin-ssot-arista-cloudvision#156]
### Environment
* Python version:  3.9
* Nautobot version:  1.5.10
* aristacv-sync version:  1.5.1

### Expected Behavior
A sync of plugin SSOT between Cloudvision and Nautobot in our dev environnement lasts 29 minutes with :  {'create': 3404, 'update': 0, 'delete': 0, 'no-change': 0, 'skip': 0} ( for 20 devices)

So the behavior expected is less then 1hours for a normal sync 

### Observed Behavior

A sync of plugin SSOT between Cloudvision and Nautobot in our prod environnement lasts more than 19 hours and it still running with :  {'create': 39685, 'update': 22, 'delete': 3, 'no-change': 2774, 'skip': 1}

The job remains stuck at this stage : Syncing from CloudvisionAdapter to NautobotAdapter...
And it never finish .

Could you check why this sync is very slow ? 

### Steps to Reproduce
1. Sync Cloudvision to Nautobot ( with 145 devices in CvaaS)
2. Wait and you wil see

**Comment by jdrew82** [comment]
Unfortunately, this is a limitation of how Jobs are built with Nautobot v1.x currently. All Jobs are single-threaded and wrapped in an atomic transaction manager. As there can be a lot of calls to get all the data from CVP this can take a bit of time. This will also be impacted by latency reaching CVP from Nautobot and resources on your Nautobot instance. If you're seeing this take 29 minutes for 145 devices that's not too bad in my experience actually. Going off your diff it looks like you've got quite a bit of data attempting to be imported and processed too so the time makes sense. When Nautobot 2.0 is released there will be a Jobs refactoring that should enable us to utilize parallelization and optimizations to improve the time for the Job to complete hopefully.

**Comment by erjac77** [comment]
Actually, it's 29min for 20 devices in our dev environment, but 19hr and more for 145 devices in our prod environment. Needless to mention that with this slowness it's almost impossible for us to use this SSoT plugin in its current state...

**Comment by jdrew82** [comment]
Oh, my mistake, I misread that. That seems very strange. I tested with a client's environment that had more than 145 devices and it wasn't taking that long. Are you using an on-prem instance or the SaaS service? When you watch the debug logs for the workers, do you see the calls taking a long time to be returned? Do these devices have a large number of interfaces? Going off the diff I'd assume that you have a large number of objects on those devices that are also being imported.

**Comment by nsicard514** [comment]
Are you using an on-prem instance or the SaaS service? : **On-prem , it's in a podman container** 

When you watch the debug logs for the workers, do you see the calls taking a long time to be returned? : 

**[2023-04-25 17:22:26,166: INFO/ForkPoolWorker-15] Created successfully
[2023-04-25 17:22:26,230: INFO/ForkPoolWorker-15] Created successfully
[2023-04-25 17:22:26,293: INFO/ForkPoolWorker-15] Created successfully
[2023-04-25 17:22:26,357: INFO/ForkPoolWorker-15] Created successfully
[2023-04-25 17:22:26,421: INFO/ForkPoolWorker-15] Created successfully
[2023-04-25 17:22:26,484: INFO/ForkPoolWorker-15] Created successfully
[2023-04-25 17:22:26,506: WARNING/MainProcess] Soft time limit (3600s) exceeded for nautobot.extras.jobs.run_job[c1045d47-ae6f-41b9-af48-b4d828077a6f]
[2023-04-25 17:22:26,506: WARNING/ForkPoolWorker-15] Exception ignored in:
[2023-04-25 17:22:26,507: WARNING/ForkPoolWorker-15] <function SDKHandleBase.__del__ at 0x7fa6ab088790>
[2023-04-25 17:22:26,507: WARNING/ForkPoolWorker-15] Traceback (most recent call last):
[2023-04-25 17:22:26,507: WARNING/ForkPoolWorker-15]   File "/opt/nautobot/.local/lib/python3.9/site-packages/oneagent/common.py", line 347, in __del__
[2023-04-25 17:22:26,509: WARNING/ForkPoolWorker-15]
[2023-04-25 17:22:26,510: WARNING/ForkPoolWorker-15] def __del__(self):
[2023-04-25 17:22:26,510: WARNING/ForkPoolWorker-15]   File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 229, in soft_timeout_sighandler
[2023-04-25 17:22:26,510: WARNING/ForkPoolWorker-15]
[2023-04-25 17:22:26,511: WARNING/ForkPoolWorker-15] raise SoftTimeLimitExceeded()
[2023-04-25 17:22:26,511: WARNING/ForkPoolWorker-15] billiard.exceptions
[2023-04-25 17:22:26,511: WARNING/ForkPoolWorker-15] .
[2023-04-25 17:22:26,511: WARNING/ForkPoolWorker-15] SoftTimeLimitExceeded
[2023-04-25 17:22:26,511: WARNING/ForkPoolWorker-15] :
[2023-04-25 17:22:26,511: WARNING/ForkPoolWorker-15] SoftTimeLimitExceeded()
[2023-04-25 17:22:26,512: ERROR/MainProcess] Task handler raised error: TimeLimitExceeded(3600)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 684, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
billiard.exceptions.TimeLimitExceeded: TimeLimitExceeded(3600,)
[2023-04-25 17:22:26,512: ERROR/MainProcess] Hard time limit (3600s) exceeded for nautobot.extras.jobs.run_job[c1045d47-ae6f-41b9-af48-b4d828077a6f]
[2023-04-25 17:22:26,626: ERROR/MainProcess] Process 'ForkPoolWorker-15' pid:72 exited with 'signal 9 (SIGKILL)'
[2023-04-26 12:42:46,188: INFO/MainProcess] Task nautobot.extras.jobs.run_job[a29667fb-54d2-4765-af22-7e2f0725fbbc] received
12:42:46.273 WARNING nautobot.jobs: The hard time limit of 3600 seconds is less than or equal to the soft time limit of 3600 seconds. This job will fail silently after 3600 seconds.
[2023-04-26 12:42:46,273: WARNING/ForkPoolWorker-17] The hard time limit of 3600 seconds is less than or equal to the soft time limit of 3600 seconds. This job will fail silently after 3600 seconds.**


Do these devices have a large number of interfaces ? **Around 96 interfaces per devices**

**Comment by nsicard514** [comment]
ERRATUM : **We use CvaaS (SaaS service) **

**Comment by jdrew82** [comment]
@nsicard514 The logs you've provided appear to show that it died during the CRUD operations updating the database and hit the Soft and Hard timeouts. Those timeouts appear to be 3600 seconds, or an hour. This doesn't align with the times that you mentioned. That sounds more like it wasn't noticed that the Job had died at the timeout. I'd advise that you increase the Soft and Hard timeout to multiple hours for now so you aren't hitting those timeouts. I'd also advise you to upgrade to Nautobot 1.5.17 and use this [feature](https://docs.nautobot.com/projects/core/en/stable/additional-features/jobs/#debugging-job-performance). This should provide more data as to why you're seeing this issue.

**Comment by erjac77** [comment]
Thanks @jdrew82 for the clarification, very interesting. We will try to change the timeout and let you know.
