### ISSUE TITLE
Error running CloudVision ⟹ Nautobot job on 1.6.0

### ISSUE THREAD

**Issue by danieltudares** [nautobot/nautobot-plugin-ssot-arista-cloudvision#159]
### Environment
* Python version:  3.10.6
* Nautobot version:  1.5.16
* nautobot-ssot: 1.2.0
* nautobot-ssot-aristacv: 1.6.0
* CloudVision on-prem: 2022.3.0

### Expected Behavior
Sync between CVP and nautobot

### Observed Behavior

Error running CloudVision ⟹ Nautobot job

### Steps to Reproduce
1. Run sync job

### troubleshooting steps

I downgraded `nautobot-ssot-aristacv` to 1.5.1 and the sync job runs properly with no issues.

**Comment by danieltudares** [comment]
This is the error received when running on debug mode: 

```
An exception occurred: `_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with: status = StatusCode.INVALID_ARGUMENT details = "element_type is required if filtering on element ID(s)" debug_error_string = "UNKNOWN:Error received from peer ipv4:172.20.20.16:443 {created_time:"2023-05-01T19:23:32.456566378+00:00", grpc_status:3, grpc_message:"element_type is required if filtering on element ID(s)"}"
```
```
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 332, in run
    self.sync_data()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 137, in sync_data
    self.load_source_adapter()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/jobs.py", line 109, in load_source_adapter
    self.source_adapter.load()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 224, in load
    self.load_devices()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 77, in load_devices
    self.load_device_tags(device=new_device)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 194, in load_device_tags
    for tag in cloudvision.get_device_tags(client=self.conn.comm_channel, device_id=device.serial)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/utils/cloudvision.py", line 323, in get_device_tags
    for resp in responses:
  File "/opt/nautobot/lib/python3.10/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/opt/nautobot/lib/python3.10/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
    status = StatusCode.INVALID_ARGUMENT
    details = "element_type is required if filtering on element ID(s)"
    debug_error_string = "UNKNOWN:Error received from peer ipv4:172.20.20.16:443 {created_time:"2023-05-01T19:23:32.456566378+00:00", grpc_status:3, grpc_message:"element_type is required if filtering on element ID(s)"}"
>
```

**Comment by the-bhattman** [comment]
I have the same issue. with a slightly different environment. 

Here is my environment

Python version: 3.10.6
Nautobot version: (v1.5.18)
nautobot-ssot: 1.3.1
nautobot-ssot-aristacv: 1.6.0
CloudVision on-prem: 2022.1.1

**ERROR Message :** "element_type is required if filtering on element ID(s)"

Output
`
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 333, in run
    self.sync_data()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 138, in sync_data
    self.load_source_adapter()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/jobs.py", line 109, in load_source_adapter
    self.source_adapter.load()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 224, in load
    self.load_devices()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 77, in load_devices
    self.load_device_tags(device=new_device)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 194, in load_device_tags
    for tag in cloudvision.get_device_tags(client=self.conn.comm_channel, device_id=device.serial)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aristacv/utils/cloudvision.py", line 323, in get_device_tags
    for resp in responses:
  File "/opt/nautobot/lib/python3.10/site-packages/grpc/_channel.py", line 475, in __next__
    return self._next()
  File "/opt/nautobot/lib/python3.10/site-packages/grpc/_channel.py", line 881, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
    status = StatusCode.INVALID_ARGUMENT
    details = "element_type is required if filtering on element ID(s)"
    debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"element_type is required if filtering on element ID(s)", grpc_status:3, created_time:"2023-05-21T21:11:26.952250699+00:00"}"`

**Comment by nsicard514** [comment]
I have the same issue with a different environment.

Python version: python3.9
Nautobot version: 1.5.19
nautobot-ssot: 1.3.1
nautobot-ssot-aristacv: 1.6.0
CloudVision CvaaS

**ERROR Message : "element_type is required if filtering on element ID(s)"**


```
Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 333, in run
    self.sync_data()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 138, in sync_data
    self.load_source_adapter()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_aristacv/jobs.py", line 109, in load_source_adapter
    self.source_adapter.load()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 224, in load
    self.load_devices()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 77, in load_devices
    self.load_device_tags(device=new_device)
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 194, in load_device_tags
    for tag in cloudvision.get_device_tags(client=self.conn.comm_channel, device_id=device.serial)
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_aristacv/utils/cloudvision.py", line 323, in get_device_tags
    for resp in responses:
  File "/opt/nautobot/.local/lib/python3.9/site-packages/grpc/_channel.py", line 475, in __next__
    return self._next()
  File "/opt/nautobot/.local/lib/python3.9/site-packages/grpc/_channel.py", line 881, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
    status = StatusCode.INVALID_ARGUMENT
    details = "element_type is required if filtering on element ID(s)"
    debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-06-11T23:00:54.814719404+00:00", grpc_status:3, grpc_message:"element_type is required if filtering on element ID(s)"}"
```

**Comment by the-bhattman** [comment]
I switched to vers: 1.5.1 from 1.6 and it worked fine.


From: Nicolas ***@***.***>
Reply-To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Date: Monday, June 12, 2023 at 9:14 AM
To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Cc: "Bhatt, Chetan" ***@***.***>, Comment ***@***.***>
Subject: Re: [nautobot/nautobot-plugin-ssot-arista-cloudvision] Error running CloudVision ⟹ Nautobot job on 1.6.0 (Issue #159)


I have the same issue with a different environment.

Python version: python3.9
Nautobot version: 1.5.19
nautobot-ssot: 1.3.1
nautobot-ssot-aristacv: 1.6.0
CloudVision CvaaS

ERROR Message : "element_type is required if filtering on element ID(s)"

Traceback (most recent call last):

  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 333, in run

    self.sync_data()

  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 138, in sync_data

    self.load_source_adapter()

  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_aristacv/jobs.py", line 109, in load_source_adapter

    self.source_adapter.load()

  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 224, in load

    self.load_devices()

  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 77, in load_devices

    self.load_device_tags(device=new_device)

  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py", line 194, in load_device_tags

    for tag in cloudvision.get_device_tags(client=self.conn.comm_channel, device_id=device.serial)

  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_aristacv/utils/cloudvision.py", line 323, in get_device_tags

    for resp in responses:

  File "/opt/nautobot/.local/lib/python3.9/site-packages/grpc/_channel.py", line 475, in __next__

    return self._next()

  File "/opt/nautobot/.local/lib/python3.9/site-packages/grpc/_channel.py", line 881, in _next

    raise self

grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:

    status = StatusCode.INVALID_ARGUMENT

    details = "element_type is required if filtering on element ID(s)"

    debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-06-11T23:00:54.814719404+00:00", grpc_status:3, grpc_message:"element_type is required if filtering on element ID(s)"}"

**Comment by nsicard514** [comment]
Yes thanks , but someone work on a fix to 1.6.0 ?

**Comment by jdrew82** [comment]
Appears to be a change with 1.6.0. We'll need some time to investigate and make a fix. Unfortunately, we don't have a 1.6.0 instance to test against so it's not going to be easy to update. Can you provide what valid values for this "element_type" var that's required? Until we resolve this I'd advise locking your CVP version to 1.5.*.

**Comment by erjac77** [comment]
If I'm not mistaken, 1.6.0 is the version of this plugin, not CVP...

**Comment by the-bhattman** [comment]
The Cloudvision version that this is failing on is 2022.1.1

**Comment by jdrew82** [comment]
Apologies, I misread the initial report and confusion over there also being a version of `cloudvision` library at 1.6.0 in the 1.5.1 release. If you're saying that it started working when you reverted to 1.5.1 then it seems like possibly one of the other dependencies got updated like CVP or `cvprac` or `python-cloudvision`. The error that you referenced is from a Stub imported from the `python-cloudvision` library which I'm assuming is where the change happened. I've confirmed that the `element_key` attribute is used in that library for Tag filtering so I'm assuming it's something related to that. Can you perhaps test this assumption by pinning your version for the cloudvision library to 1.6.0 and see if the issue persists? Unfortunately, I no longer have access to a CVP instance to test against. It is also possible it's something with the Arista Cloudvision version as I'm pretty sure I was testing against earlier versions than 2022.1.1.

**Comment by qduk** [comment]
Hello @danieltudares and @the-bhattman , can either of you verify the merge of #164 fixed the error you were getting in v1.6.0?

**Comment by danieltudares** [comment]
Hi @qduk, I wanted to acknowledge your comment and thank you for working on the fix, I'll test as soon as I can, however, I'll be on PTO with no access to my work environment for the next few weeks, so I won't be able to test until then. I'll report back once the test is done.

**Comment by the-bhattman** [comment]
Hi @qduk<https://urldefense.com/v3/__https:/github.com/qduk__;!!AQdq3sQhfUj4q8uUguY!i4i7cNzR55yP-bnvpLbn1v8eQP6rtm2Fo5CB0-OmcVBML9IELUqINfcuCzuweOLpJxJuITEcY88nxPSfcxgoMZ9PDA$>,
Thank you for following up on this. I had upgraded Nautobot recently, so I will retest it as documented and let you know in a couple of hours, if not sooner

-=CB=-

From: Adam Byczkowski ***@***.***>
Reply-To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Date: Thursday, September 14, 2023 at 8:27 AM
To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Cc: "Bhatt, Chetan" ***@***.***>, Mention ***@***.***>
Subject: Re: [nautobot/nautobot-plugin-ssot-arista-cloudvision] Error running CloudVision ⟹ Nautobot job on 1.6.0 (Issue #159)


Hello @danieltudares<https://urldefense.com/v3/__https:/github.com/danieltudares__;!!AQdq3sQhfUj4q8uUguY!hcmvzhnBGxejj5BWTo4AxId4dp-MMk-RfGN-1bnD8bQrZ8Aqqle3jImjPKrCfcjjqBJSwHu1kz73pJlqICU8CsM45w$> and @the-bhattman<https://urldefense.com/v3/__https:/github.com/the-bhattman__;!!AQdq3sQhfUj4q8uUguY!hcmvzhnBGxejj5BWTo4AxId4dp-MMk-RfGN-1bnD8bQrZ8Aqqle3jImjPKrCfcjjqBJSwHu1kz73pJlqICVikj9ugg$> , can either of you verify the merge of #164<https://urldefense.com/v3/__https:/github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision/pull/164__;!!AQdq3sQhfUj4q8uUguY!hcmvzhnBGxejj5BWTo4AxId4dp-MMk-RfGN-1bnD8bQrZ8Aqqle3jImjPKrCfcjjqBJSwHu1kz73pJlqICWvXU8FRA$> fixed the error you were getting in v1.6.0?

**Comment by the-bhattman** [comment]
Hi @qduk<https://urldefense.com/v3/__https:/github.com/qduk__;!!AQdq3sQhfUj4q8uUguY!i4i7cNzR55yP-bnvpLbn1v8eQP6rtm2Fo5CB0-OmcVBML9IELUqINfcuCzuweOLpJxJuITEcY88nxPSfcxgoMZ9PDA$>,
                I am now getting a different kind of issue.

Here is the version I am on when I tested.
Nautobot==v1.6.1
nautobot-ssot==1.4.0
nautobot_ssot_aristacv==1.6.0
nautobot_ssot_infoblox==0.8.0

It now produces this Traceback error for aristacv and Infoblox:

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/runner/runner.py", line 117, in settings_callback
    initializer(
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/cli.py", line 178, in _configure_settings
    load_plugins(settings)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/plugins/utils.py", line 54, in load_plugins
    load_plugin(plugin_name, settings)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/plugins/utils.py", line 64, in load_plugin
    plugin = importlib.import_module(plugin_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/__init__.py", line 36, in <module>
    _check_for_conflicting_apps()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/__init__.py", line 31, in _check_for_conflicting_apps
    raise RuntimeError(
RuntimeError: The following apps are installed and conflict with `nautobot-ssot`: nautobot_ssot_aristacv.

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/runner/runner.py", line 117, in settings_callback
    initializer(
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/cli.py", line 178, in _configure_settings
    load_plugins(settings)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/plugins/utils.py", line 54, in load_plugins
    load_plugin(plugin_name, settings)
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/extras/plugins/utils.py", line 64, in load_plugin
    plugin = importlib.import_module(plugin_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/__init__.py", line 36, in <module>
    _check_for_conflicting_apps()
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot/__init__.py", line 31, in _check_for_conflicting_apps
    raise RuntimeError(
RuntimeError: The following apps are installed and conflict with `nautobot-ssot`: nautobot_ssot_infoblox.




Thanks,
-=CB=-
M: 805.285.2438
[Logo  Description automatically generated]


From: "Bhatt, Chetan" ***@***.***>
Date: Thursday, September 14, 2023 at 11:14 AM
To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>, nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [nautobot/nautobot-plugin-ssot-arista-cloudvision] Error running CloudVision ⟹ Nautobot job on 1.6.0 (Issue #159)

Hi @qduk<https://urldefense.com/v3/__https:/github.com/qduk__;!!AQdq3sQhfUj4q8uUguY!i4i7cNzR55yP-bnvpLbn1v8eQP6rtm2Fo5CB0-OmcVBML9IELUqINfcuCzuweOLpJxJuITEcY88nxPSfcxgoMZ9PDA$>,
Thank you for following up on this. I had upgraded Nautobot recently, so I will retest it as documented and let you know in a couple of hours, if not sooner

-=CB=-

From: Adam Byczkowski ***@***.***>
Reply-To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Date: Thursday, September 14, 2023 at 8:27 AM
To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Cc: "Bhatt, Chetan" ***@***.***>, Mention ***@***.***>
Subject: Re: [nautobot/nautobot-plugin-ssot-arista-cloudvision] Error running CloudVision ⟹ Nautobot job on 1.6.0 (Issue #159)


Hello @danieltudares<https://urldefense.com/v3/__https:/github.com/danieltudares__;!!AQdq3sQhfUj4q8uUguY!hcmvzhnBGxejj5BWTo4AxId4dp-MMk-RfGN-1bnD8bQrZ8Aqqle3jImjPKrCfcjjqBJSwHu1kz73pJlqICU8CsM45w$> and @the-bhattman<https://urldefense.com/v3/__https:/github.com/the-bhattman__;!!AQdq3sQhfUj4q8uUguY!hcmvzhnBGxejj5BWTo4AxId4dp-MMk-RfGN-1bnD8bQrZ8Aqqle3jImjPKrCfcjjqBJSwHu1kz73pJlqICVikj9ugg$> , can either of you verify the merge of #164<https://urldefense.com/v3/__https:/github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision/pull/164__;!!AQdq3sQhfUj4q8uUguY!hcmvzhnBGxejj5BWTo4AxId4dp-MMk-RfGN-1bnD8bQrZ8Aqqle3jImjPKrCfcjjqBJSwHu1kz73pJlqICWvXU8FRA$> fixed the error you were getting in v1.6.0?

**Comment by the-bhattman** [comment]
Well that's new, but It looks like there is still documentation that reflects the old method installation with infoblox  SSOT versus this new modular method





Thanks,

Chetan Bhatt | Burbank Studios

Principal Architect - Automation & Reliability |

Global Network & Production Technology

Cell: 805.285.2438| Email: ***@***.***

________________________________

**Comment by jdrew82** [comment]
If you're running the latest version of SSoT framework, ie `nautobot-plugin-ssot` then that has the Cloudvision SSoT integrated into it. This repo is being archived and all work will be done in the nautobot-plugin-ssot repo instead. Once you upgrade to the 1.4.0 or 1.5.0 of SSoT then you'll need to disable this package as it will cause a conflict. There are details of how to do this [here](https://docs.nautobot.com/projects/ssot/en/latest/admin/integrations/aristacv_setup/#configuration).

**Comment by the-bhattman** [comment]
Now I am getting the following error, when Did the new method

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "extras_job_grouping_name_8cbc9328_uniq"
DETAIL:  Key ("grouping", name)=(SSoT - Arista CloudVision, CloudVision ⟹ Nautobot) already exists.

It appears there is a duplicate key in the postgres database.



Thanks,
-=CB=-
M: 805.285.2438
[Logo  Description automatically generated]


From: Justin Drew ***@***.***>
Reply-To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Date: Wednesday, September 20, 2023 at 10:09 AM
To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Cc: "Bhatt, Chetan" ***@***.***>, Mention ***@***.***>
Subject: Re: [nautobot/nautobot-plugin-ssot-arista-cloudvision] Error running CloudVision ⟹ Nautobot job on 1.6.0 (Issue #159)


If you're running the latest version of SSoT framework, ie nautobot-plugin-ssot then that has the Cloudvision SSoT integrated into it. This repo is being archived and all work will be done in the nautobot-plugin-ssot repo instead. Once you upgrade to the 1.4.0 or 1.5.0 of SSoT then you'll need to disable this package as it will cause a conflict. There are details of how to do this here<https://urldefense.com/v3/__https:/docs.nautobot.com/projects/ssot/en/latest/admin/integrations/aristacv_setup/*configuration__;Iw!!AQdq3sQhfUj4q8uUguY!hA6c84kbIQXaSfRtq1RtbpJu_EeUmrPm60mEF3t_nE-M3dYYA82-zcVbqSdumplNnrylYJRiyHh3y_nK0IjNXXFDsg$>.

**Comment by the-bhattman** [comment]
I finally resolved the issue.

Looking at Postgress SQL database under the extras_job  schema, there were 2 records left over from when Nautobot was separate module. For whatever, reason it was not removed in the process of the migration.

I had to manually delete the entry in Postgress.

nautobot=> DELETE FROM extras_job WHERE id='38990d9f-d5d5-4fe7-a8d5-d6984c4e4d50';
DELETE 1
nautobot=> DELETE FROM extras_job WHERE id='c8da32a0-7e7d-46b6-8dd1-da5301b47232';
DELETE 1



Thanks,
-=CB=-
M: 805.285.2438
[Logo  Description automatically generated]


From: "Bhatt, Chetan" ***@***.***>
Date: Sunday, September 24, 2023 at 12:37 AM
To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>, nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [nautobot/nautobot-plugin-ssot-arista-cloudvision] Error running CloudVision ⟹ Nautobot job on 1.6.0 (Issue #159)

Now I am getting the following error, when Did the new method

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "extras_job_grouping_name_8cbc9328_uniq"
DETAIL:  Key ("grouping", name)=(SSoT - Arista CloudVision, CloudVision ⟹ Nautobot) already exists.

It appears there is a duplicate key in the postgres database.



Thanks,
-=CB=-
M: 805.285.2438
[Logo  Description automatically generated]


From: Justin Drew ***@***.***>
Reply-To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Date: Wednesday, September 20, 2023 at 10:09 AM
To: nautobot/nautobot-plugin-ssot-arista-cloudvision ***@***.***>
Cc: "Bhatt, Chetan" ***@***.***>, Mention ***@***.***>
Subject: Re: [nautobot/nautobot-plugin-ssot-arista-cloudvision] Error running CloudVision ⟹ Nautobot job on 1.6.0 (Issue #159)


If you're running the latest version of SSoT framework, ie nautobot-plugin-ssot then that has the Cloudvision SSoT integrated into it. This repo is being archived and all work will be done in the nautobot-plugin-ssot repo instead. Once you upgrade to the 1.4.0 or 1.5.0 of SSoT then you'll need to disable this package as it will cause a conflict. There are details of how to do this here<https://urldefense.com/v3/__https:/docs.nautobot.com/projects/ssot/en/latest/admin/integrations/aristacv_setup/*configuration__;Iw!!AQdq3sQhfUj4q8uUguY!hA6c84kbIQXaSfRtq1RtbpJu_EeUmrPm60mEF3t_nE-M3dYYA82-zcVbqSdumplNnrylYJRiyHh3y_nK0IjNXXFDsg$>.

**Comment by qduk** [comment]
@the-bhattman I actually ran into this a couple of days ago with a different SSoT integration. Glad it has been figured out. If there are any other issues please open them in the [nautobot-plugin-ssot](https://github.com/nautobot/nautobot-plugin-ssot) repo. Thank you!
